# Generated by Django 4.2.5 on 2023-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vocab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_ko", models.CharField(max_length=100, verbose_name="Meaning")),
                (
                    "word_fo",
                    models.CharField(blank=True, max_length=100, verbose_name="Vocab"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en-US", "English"),
                            ("ja-JP", "Japanese"),
                            ("zh-CN", "Chinese"),
                            ("es-ES", "Spanish"),
                            ("fr-FR", "French"),
                            ("de-DE", "German"),
                            ("ru-RU", "Russian"),
                        ],
                        default="en-US",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("sentence", models.TextField(blank=True, verbose_name="Sentence")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
            ],
        ),
    ]
