# Generated by Django 4.2.5 on 2023-10-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("langapp", "0002_vocab_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="author",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
