# Generated by Django 4.2.5 on 2023-10-05 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("langapp", "0004_alter_vocab_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocab",
            name="id",
        ),
        migrations.AlterField(
            model_name="vocab",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_ko",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Meaning",
            ),
        ),
    ]
